name: r2s Lienol版openwrt

on:
  push:
    branches: 
      - master
    paths:
      - '.github/workflows/r2s_lienol.yml'
  schedule:
    - cron: '30 09 * * *'

jobs:

  build:
    
    runs-on: ubuntu-latest
    if: github.repository == 'klever1988/nanopi-openwrt'
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d
          sudo apt-get update
          sudo apt-get -y install bc build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          
      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
          
      - name: Init Source
        run: |
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.1 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle --depth=1
          repo sync -c --no-tags --no-clone-bundle -j8
          cd friendlywrt/ && git fetch --unshallow
          
      - name: Patch Kernel
        run: |
          . patch_kernel_5.4.22.sh
                    
      - name: Mods
        run: |
          cd friendlywrt-rk3328
          . ../remove_unused_config.sh
          cat configs/config_rk3328 | grep "TARGET" >> ../base_rk3328.seed
          cat ../app_config.seed >> ../base_rk3328.seed
          cat ../base_rk3328.seed > configs/config_rk3328
          cd friendlywrt
          git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
          git remote add upstream https://github.com/Lienol/openwrt && git fetch upstream
          git checkout upstream/dev-19.07 -b tmp
          git mv README.md README && git commit -m 'undo rename readme for rebasing'
          git checkout origin/master-v19.07.1
          git rebase adc1a9a3676b8d7be1b48b5aed185a94d8e42728^ --onto tmp -X theirs
          git revert --no-edit f092ca098e80c667b10cdd1dba328506a2673c1d
          git checkout upstream/dev-19.07 -- feeds.conf.default
          sed -i '/exit/i\chown -R root:root /usr/share/netdata/web' package/default-settings/files/zzz-default-settings
          sed -i 's/option fullcone\t1/option fullcone\t0/' package/network/config/firewall/files/firewall.config
          sed -i '/8.8.8.8/d' package/base-files/files/root/setup.sh
          echo -e '\nDYC Build\n'  >> package/base-files/files/etc/banner
          #sed -i '/#/d' target/linux/rockchip-rk3328/config-4.14 #fix compile error
          #sed -i '/CONFIG_BLK_CGROUP/a\CONFIG_DEBUG_BLK_CGROUP=y' target/linux/rockchip-rk3328/config-4.14 #as above
          #sed -i '/CONFIG_BLK_CGROUP/a\CONFIG_CFS_BANDWIDTH=y' target/linux/rockchip-rk3328/config-4.14 #as above
          #sed -i '/CONFIG_BLK_CGROUP/a\CONFIG_RT_GROUP_SCHED=y' target/linux/rockchip-rk3328/config-4.14 #as above
          #sed -i '/CONFIG_BLK_CGROUP/a\CONFIG_CGROUP_FREEZER=y' target/linux/rockchip-rk3328/config-4.14 #as above
          sed -i '/CONFIG_BLK_CGROUP/a\CONFIG_CGROUP_PERF=y' target/linux/rockchip-rk3328/config-4.14 #as above
          
      - name: Mod luci
        run: |
          cd friendlywrt-rk3328/friendlywrt
          ./scripts/feeds update -a && ./scripts/feeds install -a
          sed -i '/Load Average/i\<div class="tr"><div class="td left" width="33%"><%:CPU Temperature%></div><div class="td left" id="_cputemp"><%=luci.sys.exec("cut -c1-2 /sys/class/thermal/thermal_zone0/temp")%></div></div>' feeds/luci/modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
          sed -i 's/pcdata(boardinfo.system or "?")/"ARMv8"/' feeds/luci/modules/luci-mod-admin-full/luasrc/view/admin_status/index.htm
          
      - name: Build FriendlyWrt
        run: |
          cd friendlywrt-rk3328
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          ./build.sh nanopi_r2s.mk
      
      - name: Zip Files
        run: |
          gzip friendlywrt-rk3328/out/*.img
      - name: Assemble Artifact
        id: assemble_artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          mv friendlywrt-rk3328/out/*img* ./artifact/
          cp friendlywrt-rk3328/friendlywrt/.config ./artifact/
          zip -r artifact.zip ./artifact/
          release_tag="R2S-Lienol-$(date +%Y-%m-%d)"
          echo "##[set-output name=release_tag;]$release_tag"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.sec_token }}
        with:
          tag_name: ${{ steps.assemble_artifact.outputs.release_tag }}
          release_name: 自动发布 ${{ steps.assemble_artifact.outputs.release_tag }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.sec_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./artifact.zip
          asset_name: ${{ steps.assemble_artifact.outputs.release_tag }}-ROM.zip
          asset_content_type: application/zip
