name: r2s Lienolç‰ˆopenwrt

on:
  push:
    paths:
      - '.github/workflows/r2s_lienol.yml'
  schedule:
    - cron: '30 12 * * *'

jobs:

  build:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d
          sudo apt-get update
          sudo apt-get -y install bc build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk
          
      - name: Install Repo
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
          
      - name: Init Source
        run: |
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo  --no-clone-bundle
          cp ../rk3328-19.xml .repo/manifests/rk3328.xml
          repo sync -c  --no-clone-bundle
          rm -rf friendlywrt/
          git clone https://github.com/friendlyarm/friendlywrt
          
      - name: Mods
        run: |
          cd friendlywrt-rk3328
          . ../remove_used_config.sh
          echo '
          CONFIG_OPENSSL_ENGINE_BUILTIN=y
          CONFIG_OPENSSL_OPTIMIZE_SPEED=y
          CONFIG_OPENSSL_WITH_DTLS=y
          CONFIG_OPENSSL_WITH_EC2M=y
          CONFIG_OPENSSL_WITH_NPN=y
          CONFIG_PACKAGE_ca-bundle=y
          CONFIG_PACKAGE_curl=y
          CONFIG_PACKAGE_libcurl=y
          CONFIG_PACKAGE_luci-app-netdata=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan=y
          CONFIG_PACKAGE_luci-app-smartdns=y
          CONFIG_PACKAGE_luci-i18n-netdata-zh-cn=y
          CONFIG_PACKAGE_luci-i18n-smartdns-zh-cn=y
          CONFIG_PACKAGE_luci-theme-argon-dark-mod=y
          CONFIG_PACKAGE_luci-theme-argon-light-mod=y
          CONFIG_PACKAGE_luci-theme-freifunk-generic=y
          CONFIG_PACKAGE_luci-theme-material=y
          CONFIG_PACKAGE_luci-theme-netgear-mc=y
          CONFIG_PACKAGE_luci-theme-openwrt=y' >> configs/config_rk3328
          cd friendlywrt
          git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
          git remote add upstream https://github.com/Lienol/openwrt && git fetch upstream
          git checkout upstream/dev-19.07 -b tmp
          git revert --no-edit 2202533d29c1494ad5645f87a7429e70f85a0110
          git mv README.md README && git commit -m 'undo rename readme for rebasing'
          git checkout origin/master-v19.07.1
          git rebase adc1a9a3676b8d7be1b48b5aed185a94d8e42728^ --onto tmp -X theirs
          #git cherry-pick origin/master 8f734f05f11b9f94af3cf1469537587ef102e5f2^...origin/HEAD
          git checkout upstream/dev-19.07 -- feeds.conf.default
          #sed -i '/exit/i\echo "iptables -t nat -I POSTROUTING -j MASQUERADE" >> /etc/firewall.user' package/default-settings/files/zzz-default-settings
          sed -i 's/option fullcone\t1/option fullcone\t0/' package/network/config/firewall/files/firewall.config
          sed -i '/8.8.8.8/d' package/base-files/files/root/setup.sh
          
      - name: Clean Feeds
        run: |
          cd friendlywrt-rk3328/friendlywrt
          ./scripts/feeds clean -a
                    
      - name: Build FriendlyWrt
        run: |
          cd friendlywrt-rk3328
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          ./build.sh nanopi_r2s.mk
      
      - name: Zip Files
        run: |
          gzip friendlywrt-rk3328/out/*.img
      - name: Assemble Artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          mv friendlywrt-rk3328/out/*img* ./artifact/
          cp friendlywrt-rk3328/friendlywrt/.config ./artifact/
      - name: Upload Artifact
        uses: actions/upload-artifact@master
        with:
          name: FriendlyWrt_NanoPi-R2S
          path: ./artifact/
