name: r5s-fuse-test

on:
  push:
    branches: [ r5s-fuse ]
    paths:
      - '.github/workflows/r5s.yml'
  schedule:
    - cron: '10 09 * * *'

jobs:

  build:

    runs-on: ubuntu-18.04
    if: github.repository == 'klever1988/nanopi-openwrt'

    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: . 1_initialization_environment.sh

      - name: Clone Source
        run: . 2_clone_source.sh master-v22.03 rk3568.xml

      - name: Mods
        run: |
          cd friendlywrt-rk3568
          . ../remove_unused_config.sh
          #cat configs/config_rk3328 | grep "TARGET" >> ../base_rk3328.seed
          #cat ../app_config.seed >> ../base_rk3328.seed
          #cat ../base_rk3328.seed > configs/config_rk3328
          cd friendlywrt
          git remote add upstream https://github.com/coolsnowwolf/lede && git fetch upstream
          git checkout upstream/master -b tmp
          git checkout master-v22.03
          git rebase efcced5190bfd69ff438073853494f711a384052^ --onto tmp -X theirs
          #. ../../3_prepare_packages.sh
          . ../../5_mods.sh

      - name: Build FriendlyWrt
        run: . 4_build_image.sh friendlywrt-rk3568 nanopi_r5s.mk

      - name: Assemble Artifact
        id: assemble_artifact
        run: |
          . x_assemble_artifact.sh
          release_tag="r5s-Lean-$(date +%Y-%m-%d)"
          echo "##[set-output name=release_tag;]$release_tag"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.sec_token }}
        with:
          tag_name: ${{ steps.assemble_artifact.outputs.release_tag }}
          release_name: 自动发布 ${{ steps.assemble_artifact.outputs.release_tag }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.sec_token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./artifact.zip
          asset_name: ${{ steps.assemble_artifact.outputs.release_tag }}-ROM.zip
          asset_content_type: application/zip
